spring.application.name=hpms

# ==========================================
# DATABASE - PostgreSQL
# ==========================================

spring.datasource.url=jdbc:postgresql://localhost:5432/hpms
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=aarisha2006

# ==========================================
# JPA / HIBERNATE
# ==========================================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false

# ==========================================
# SERVER
# ==========================================

server.port=8080

# ==========================================
# JWT
# ==========================================

hpms.jwt.secret=CHANGE_THIS_TO_A_LONG_RANDOM_256BIT_SECRET_BEFORE_DEPLOYING_HPMS
hpms.jwt.expiration-patient-ms=14400000
hpms.jwt.expiration-staff-ms=28800000
hpms.jwt.expiration-admin-ms=43200000

# ==========================================
# AES-256 KEY FOR PHI FIELD ENCRYPTION
# ==========================================

hpms.security.aes-key=NoVWOtWUQAXtmoK3MBoMTuRLnyxqNjYDTyIdVnNKUCM=

# ==========================================
# CORS
# ==========================================

hpms.cors.allowed-origins=http://localhost:5173,http://localhost:8081